const CARS = {
    GOT_CARS: 'GOT_CARS',
    GOT_SINGLECAR: 'GOT_SINGLECAR',
    ADDED_CAR: 'ADDED_CAR',
    EDITED_CAR: 'EDITED_CAR',
    REMOVED_CAR: 'REMOVED_CAR',
    REQUESTED_CAR: 'REQUESTED_CAR',
    LOAD_FAILED: 'LOAD_FAILED',
}

export default CARS;
