const CARTS = {
  GOT_CARTS: 'GOT_CARTS',
  GOT_SINGLE_CART: 'GOT_SINGLE_CART',
  ADDED_CART: 'ADDED_CART',
  REMOVED_CART: 'REMOVED_CART',
  EDITED_CART: 'EDITED_CART',
  REQUESTED_CART: 'REQUESTED_CART',
  LOAD_FAILED: 'LOAD_FAILED',
};

export default CARTS;
