const TRANSACTIONS = {
  GOT_TRANSACTIONS: 'GOT_TRANSACTIONS',
  GOT_SINGLETRANSACTION: 'GOT_SINGLETRANSACTION',
  ADDED_TRANSACTION: 'ADDED_TRANSACTION',
  REMOVED_TRANSACTION: 'REMOVED_TRANSACTION',
  EDITED_TRANSACTION: 'EDITED_TRANSACTION'
};

export default TRANSACTIONS;
