const USERS = {
    GOT_USERS: 'GOT_USERS',
    GOT_SINGLE_USER: 'GOT_SINGLE_USER',
    ADDED_USER: 'ADDED_USER',
    REMOVE_USER: 'REMOVE_USER',
    EDITED_USER: 'EDITED_USER',
    REQUESTED_USER: 'REQUESTED_USER',
    LOAD_FAILED: 'LOAD_FAILED',

}

export default USERS
